demo:
  phone: 111111111
  sex: 男
  address: 河南
  identity: student,person,Chinese
  cars:
    - 大众
    - 宝马
    - 奥迪
  maps: "{'money': '1000','age': '22'}"
  girlfriend:
    name: 美女
    age: 20

list:
  girlfriendList:
   - name: 好人
     age: 24
   - name: 坏人
     age: 23