# 配置服务端口号
server:
  port: 8081
# 服务名
spring:
  profiles:
    active: prod
  application:
    name: springboot-helloworld
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  # 静态资源路径配置
  resources:
    static-locations: classpath:/static