server:
  port: 8981
spring:
  application:
    name: springboot-actuator
management:
  endpoints:
    # 暴露 EndPoint 以供访问,有jmx和web两种方式,exclude 的优先级高于 include
    jmx:
      exposure:
        exclude: '*'
        include: '*'
    web:
      exposure:
        # exclude: '*'
        include: '*'
        # [ "health","info","beans","mappings","logfile","metrics","shutdown","env","prometheus" ]
      base-path: /actuator  # 配置 Endpoint 的基础路径
      cors: # 配置跨域资源共享
        allowed-origins: http://example.com
        allowed-methods: GET,POST
    enabled-by-default: true # 修改全局 endpoint 默认设置
  endpoint:
    auditevents:
      enabled: true # 显示当前引用程序的审计事件信息,默认开启
      cache:
        time-to-live: 10s # 配置端点缓存响应的时间
    beans:
      enabled: true # 显示一个应用中所有 Spring Beans 的完整列表,默认开启
    conditions:
      enabled: true # 显示配置类和自动配置类的状态及它们被应用和未被应用的原因,默认开启
    configprops:
      enabled: true # 显示一个所有@ConfigurationProperties的集合列表,默认开启
    env:
      enabled: true # 显示来自Spring的 ConfigurableEnvironment的属性,默认开启
    flyway:
      enabled: true # 显示数据库迁移路径,如果有的话,默认开启
    health:
      enabled: true # 显示健康信息,默认开启
      show-details: always
    info:
      enabled: true # 显示任意的应用信息,默认开启
    liquibase:
      enabled: true # 展示任何Liquibase数据库迁移路径,如果有的话,默认开启
    metrics:
      enabled: true # 展示当前应用的metrics信息,默认开启
    mappings:
      enabled: true # 显示一个所有@RequestMapping路径的集合列表,默认开启
    scheduledtasks:
      enabled: true # 显示应用程序中的计划任务,默认开启
    sessions:
      enabled: true # 允许从Spring会话支持的会话存储中检索和删除(retrieval and deletion)用户会话。使用Spring Session对反应性Web应用程序的支持时不可用。默认开启。
    shutdown:
      enabled: true # 允许应用以优雅的方式关闭,默认关闭
    threaddump:
      enabled: true # 执行一个线程dump
    # web 应用时可以使用以下端点
    heapdump:
      enabled: true  # 返回一个GZip压缩的hprof堆dump文件,默认开启
    jolokia:
      enabled: true # 通过HTTP暴露JMX beans(当Jolokia在类路径上时,WebFlux不可用),默认开启
    logfile:
      enabled: true # 返回日志文件内容(如果设置了logging.file或logging.path属性的话),支持使用HTTP Range头接收日志文件内容的部分信息,默认开启
    prometheus:
      enabled: true # 以可以被Prometheus服务器抓取的格式显示metrics信息,默认开启
info:
  java: @java.version@
  springboot: @spring-boot.version@
