spring:
  redis:
    # redis数据库地址
    host: localhost
    port: 6379
    max-wait: 3000 # 连接池最大连接数（使用负值表示没有限制）
    max-active: 8 # 连接池最大阻塞等待时间（使用负值表示没有限制）
    max-idle: 8 # 连接池中的最大空闲连接
    min-idle: 0 # 连接池中的最小空闲连接
    timeout: 1000 # 连接超时时间（毫秒）
    # redis数据库索引，默认0
    database: 0
    jedis:
      pool:
        max-active: 1024 # 连接池最大连接数（使用负值表示没有限制）
        max-wait: 10000 # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 200 # 连接池中的最大空闲连接
        min-idle: 0 # 连接池中的最小空闲连接
    block-when-exhausted: true # redis配置结束
