# springboot 2.3.X 以前版本配置方法
#spring:
#  data:
#    elasticsearch:
#      cluster-nodes: 192.168.37.128:9300
#      cluster-name: my-elasticsearch
#      repositories:
#        enabled: true
spring:
  elasticsearch:
    rest:
      uris: http://localhost:9200
      read-timeout: 10s
